services:

  ros2_environment:
    container_name: ros_environment
    runtime: nvidia
    build:
      context: .
      dockerfile: ros.dockerfile
      args:
        UID: ${HOST_UID}
        GID: ${HOST_GID}
    devices:
    - /dev/snd
    - /dev/bus/usb
    - /dev/video0
    - /dev/video1
    group_add:
    - audio
    - "44"
    # - video
    environment:
      - PULSE_SERVER=unix:/run/user/1000/pulse/native
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - SDL_VIDEODRIVER=x11
      - ROS_DOMAIN_ID=0
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=graphics,utility,compute

      
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${HOME}/.Xauthority:/home/ros/.Xauthority:rw
      - /dev/dri:/dev/dri 
      - ./src:/home/ros/ws/src
      - /run/user/1000/pulse/native:/run/user/1000/pulse/native
    ports:
      - "5173:5173"
      - "9090:9090"
    stdin_open: true
    tty: true
    networks:
      - app_net

  server_environment:
    container_name: server_environment
    build:
      context: .
      dockerfile: server.dockerfile
      args:
        UID: ${HOST_UID}
        GID: ${HOST_GID}
    environment:
      DATABASE_URL: postgresql+psycopg2://admin:admin123@db:5432/library
    volumes:
      - ./src/backend:/app
      - ./src/server_data:/app/server_data
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - app_net

  db:
    image: pgvector/pgvector:pg16
    container_name: library_db
    # change this later for security
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    volumes:
    - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app_net

  
  librarian_ui:
    container_name: librarian_ui
    image: node:20
    working_dir: /app
    volumes:
      - ./src/frontend/librarian_frontend:/app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    ports:
      - "5174:5173" 
    networks:
      - app_net

volumes:
  postgres_data:

networks:
  app_net:
    driver: bridge
